# Stakeholders

| **Stakeholder**                          | **Influencia**                                                                                                                                   | **Interés**                                                                                                                                       |
|------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------|
| Núcleo del equipo (Nuthelk, Daniela, Karol) | Alta. Son responsables directos del diseño, prototipado y gestión del proyecto. Toman decisiones clave en metodología, funcionalidades y entregables. | Alto. Su interés radica en cumplir con los objetivos, aplicar sus conocimientos y desarrollar una solución viable que pueda ser escalable a futuro. |
| Usuarios finales (estudiantes universitarios de Colombia) | Media-Alta. Aunque no deciden sobre el desarrollo, sus necesidades y retroalimentación determinan el éxito del proyecto. | Muy alto. Están directamente interesados en acceder a una plataforma que centralice materiales, facilite el aprendizaje y fomente el intercambio de habilidades. |
| Sponsors/Interesados (posibles inversionistas o universidades) | Alta. En caso de apoyar el proyecto, pueden aportar financiamiento, visibilidad y validación institucional. | Medio-Alto. Su interés depende del impacto del proyecto y su viabilidad de implementación en un contexto real. |
| Docentes y tutores universitarios         | Media. Pueden influir indirectamente recomendando el uso de la plataforma o contribuyendo con materiales y validación académica. | Medio. Pueden beneficiarse al tener estudiantes mejor preparados y con recursos accesibles. |
| Entorno académico/universidades           | Media-Alta. Su participación puede garantizar legitimidad y sostenibilidad a largo plazo. | Alto. Interesadas en fomentar innovación y mejorar la experiencia académica de sus estudiantes. |

*Tabla 3. Stakeholders*
